name: Pull Request - Java Build & Lint & beta release

on: [pull_request]

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '17.0.1'

    - name: Run Linter
      run: bash .githooks/pre-commit.sh

    - name: Cache Gradle dependendies
      uses: actions/cache@v4
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
 
    - name: Build with Gradle
      run: bash ./gradlew build --info

    - name: Load Release JSON Config
      uses: rgarcia-phi/json-to-variables@v1.1.0
      with:
        filename: 'release-config.json'
        prefix: release

    - name: Show Release Version
      id: release-info
      env:
        RUN_ID: ${{ github.run_id }}
      run: |
        git fetch --tags
        last_version=$(git tag -l "${{ env.release_major_version }}.${{ env.release_minor_version }}.*" --sort=v:refname | tail -1)
        last_patch=$(cut -d '.' -f 3 <<< "$last_version")
        new_patch="$(($last_patch + 1))" # TODO: Start from zero if not set
        my_version="${{ env.release_major_version }}.${{ env.release_minor_version }}.$new_patch.beta-${{ env.RUN_ID }}"
        echo "Output [$my_version]"
        echo "version=$my_version" >> $GITHUB_OUTPUT

    - name: Publish with Gradle
      run: bash ./gradlew publish --info
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_VERSION: ${{ steps.release-info.outputs.version }}

    - name: Send Jar Link to PR
      uses: actions/github-script@v6
      env:
        JAR_VERSION: ${{ steps.release-info.outputs.version }}
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `The ${process.env.JAR_VERSION} package for this MR can be found here: https://github.com/Manchester-Central/CHAOS-Shared-Code/packages/2033853?version=${process.env.JAR_VERSION}`
          })
